
#define SUBSAMPLING_MODE_4_4_4 3
#define SUBSAMPLING_MODE_4_2_2 2

#define ALPHA_CHANNEL_DISABLED 0
#define ALPHA_CHANNEL_INT8  1
#define ALPHA_CHANNEL_INT16 2

#define SCANNING_MODE_PROGRESSIVE 0
#define SCANNING_MODE_INTERLACED 1

